before:
  hooks:
    - go mod tidy

builds:
  - id: mear-cli
    main: ./cmd/cli
    binary: mear
    env:
      - CGO_ENABLED=0
  - id: mear-host
    main: ./cmd/host
    binary: mear-host
    env:
      - CGO_ENABLED=0
  - id: mear-agent
    main: ./cmd/agent
    binary: mear-agent
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archives:
  - id: mear-cli
    builds:
    - mear-cli
    format: binary
  - id: mear-host
    builds:
    - mear-host
    format: binary
  - id: mear-agent
    builds:
    - mear-agent
    format: binary
