version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - mear-network
  minio:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z.hotfix.0fb43447e
    restart: unless-stopped
    command:
      - server
      - /data
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - mear-network
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/minio/health/live
      interval: 30s
      timeout: 20s
      retries: 3
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
volumes:
  minio-data:
networks:
  mear-network:
    external: true
