version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - mear-network
  minio-source:
    image: minio/minio
    restart: unless-stopped
    command:
      - server
      - /data
    volumes:
      - minio-source-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - mear-network
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/minio/health/live
      interval: 30s
      timeout: 20s
      retries: 3
  minio-destination:
    image: minio/minio
    restart: unless-stopped
    command:
      - server
      - /data
    volumes:
      - minio-destination-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - mear-network
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/minio/health/live
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  minio-source-data:
  minio-destination-data:
networks:
  mear-network:
    external: true
